package vistas;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import modelo.EntidadVendedor;
import modelo.VendedorDAO;
public class Principal extends javax.swing.JFrame {
    EntidadVendedor pr= new EntidadVendedor();
    VendedorDAO PrDAO = new VendedorDAO();
     DefaultTableModel modelo;
   
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSubMenuSalir = new javax.swing.JMenuItem();
        jMenuVentas = new javax.swing.JMenu();
        jSubmenuGenerarVenta = new javax.swing.JMenuItem();
        jMenuMantenimiento = new javax.swing.JMenu();
        jSubMenuCliente = new javax.swing.JMenuItem();
        jSubMenuProducto = new javax.swing.JMenuItem();
        jSubMenuVendedor = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jSubMenuReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTANA PRINCIPAL MODANNA");

        VentanaPrincipal.setBackground(new java.awt.Color(255, 255, 153));
        VentanaPrincipal.setForeground(new java.awt.Color(250, 240, 181));

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu3.png"))); // NOI18N
        jMenuPrincipal.setText("Menú");
        jMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipalActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ayuda");
        jMenuPrincipal.add(jMenuItem1);

        jSubMenuSalir.setText("Salir");
        jSubMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuSalirActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jSubMenuSalir);

        jMenuBar1.add(jMenuPrincipal);

        jMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrrito3.png"))); // NOI18N
        jMenuVentas.setText("Ventas");
        jMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVentasActionPerformed(evt);
            }
        });

        jSubmenuGenerarVenta.setText("Generar Venta");
        jSubmenuGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmenuGenerarVentaActionPerformed(evt);
            }
        });
        jMenuVentas.add(jSubmenuGenerarVenta);

        jMenuBar1.add(jMenuVentas);

        jMenuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento4.png"))); // NOI18N
        jMenuMantenimiento.setText("Mantenimiento");

        jSubMenuCliente.setText("Cliente");
        jSubMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuClienteActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jSubMenuCliente);

        jSubMenuProducto.setText("Producto");
        jSubMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuProductoActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jSubMenuProducto);

        jSubMenuVendedor.setText("Vendedor");
        jSubMenuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuVendedorActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jSubMenuVendedor);

        jMenuBar1.add(jMenuMantenimiento);

        jMenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes5.png"))); // NOI18N
        jMenuReportes.setText("Reportes");

        jSubMenuReporte.setText("Reporte de Ventas");
        jSubMenuReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuReporteActionPerformed(evt);
            }
        });
        jMenuReportes.add(jSubMenuReporte);

        jMenuBar1.add(jMenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSubMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuProductoActionPerformed
        ProductosFrom vproducto= new ProductosFrom();
        VentanaPrincipal.add(vproducto);
        //CentrarVentana(vproducto);
        vproducto.setVisible(true);
    }//GEN-LAST:event_jSubMenuProductoActionPerformed

    private void jMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipalActionPerformed
       
    }//GEN-LAST:event_jMenuPrincipalActionPerformed

    private void jSubmenuGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmenuGenerarVentaActionPerformed
        VentasFrom gv= new VentasFrom();
        VentanaPrincipal.add(gv);
        gv.setVisible(true);
       // gv.setVisible(false);
        //CentrarVentana(gv);
    }//GEN-LAST:event_jSubmenuGenerarVentaActionPerformed
    void CentrarVentana(JInternalFrame frame){
        VentanaPrincipal.add(frame);
        Dimension dimension= VentanaPrincipal.getMaximumSize();
        Dimension Dframe=frame.getSize();
        frame.setLocation((dimension.width -Dframe.width)/2, (dimension.height-Dframe.height)/2);
        frame.show();
    }
    private void jMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVentasActionPerformed
        //VentasFrom gestionarventas=new VentasFrom();
       // CentrarVentana(gestionarventas);  
    }//GEN-LAST:event_jMenuVentasActionPerformed

    private void jSubMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuClienteActionPerformed
        ClienteFrom vcliente= new ClienteFrom();
        VentanaPrincipal.add(vcliente);
        //CentrarVentana(vcliente);
        vcliente.setVisible(true);
    }//GEN-LAST:event_jSubMenuClienteActionPerformed

    private void jSubMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuSalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jSubMenuSalirActionPerformed

    private void jSubMenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuVendedorActionPerformed
        VendedorFrom vf = new VendedorFrom();
        VentanaPrincipal.add(vf);
        //CentrarVentana(vf);
        vf.setVisible(true);
        
    }//GEN-LAST:event_jSubMenuVendedorActionPerformed

    private void jSubMenuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuReporteActionPerformed
      ReportesFrom rf = new ReportesFrom();
        VentanaPrincipal.add(rf);
        rf.setVisible(true);
       // rf.setVisible(false);
    }//GEN-LAST:event_jSubMenuReporteActionPerformed
    
    /**¿
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuMantenimiento;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JMenuItem jSubMenuCliente;
    private javax.swing.JMenuItem jSubMenuProducto;
    private javax.swing.JMenuItem jSubMenuReporte;
    private javax.swing.JMenuItem jSubMenuSalir;
    private javax.swing.JMenuItem jSubMenuVendedor;
    private javax.swing.JMenuItem jSubmenuGenerarVenta;
    // End of variables declaration//GEN-END:variables
}
